# Generated by Django 5.2 on 2025-05-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')])),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('tID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.CharField(default='Math', max_length=60)),
                ('sID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs348proj.student')),
            ],
        ),
    ]
