# Generated by Django 5.2 on 2025-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs348proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sID',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
